# Introduction to Python for scientific research
*Bart van Stratum, Max Planck Institute for Meteorology, Hamburg*

AES Python workshop, 7-8 October 2015, MPI-M

This notebook is available at https://github.com/julietbravo/python_workshop_AES 
(http://nbviewer.ipython.org/github/julietbravo/python_workshop_AES/blob/master/Python_introduction.ipynb)

# 1 Introduction
### The origin of Python

> *"Over six years ago, in December 1989, I was looking for a "hobby" programming project that would keep me occupied during the week around Christmas...”* — Guido van Rossum

### Python: general-purpose, high-level programming language 
* General purpose: more than a plotting language!  
􏰀  * One of the key languages at e.g. Google, CERN, NASA   
* High-level: focus on code readability, short syntax  
* Interpreted language

### Why use Python for your research?
*(my personal opinion, and in random order)*

1. Easy to learn, and read / write code
2. It's free! (unlike Matlab, IDL, ...)
3. Well documented (I'll get back to that), easy to get support (Stackoverflow)
4. Capable of handling your entire scientific workflow

### Python 2 vs. Python 3
Extensive discussion at https://wiki.python.org/moin/Python2orPython3
> Python 2.x is legacy, Python 3.x is the present and future

* Python 3: released in 2008, stable and actively developed version, currently at version 3.5
* Python 2: last release in 2010, maintained but not actively developed
  
Python 3 = backwards-incompatible release! Some Python 3 features backported to 2.7

#### My recommendation: use Python 3

# 2 Getting started with Python
## 2.1 Install or load Python
Python core by default installed on (almost?) all Linux distributions and OS X. Useful extensions (discussed later) available through package managers  

##### On MPI systems (desktops, Thunder): 
* `module load python` (Python 2.7)
* `module load python3/3.4.2` (Python 3.4)

##### OS X using Macports:
* `sudo port install python34 py34-ipython py34-numpy py34-matplotlib py34-netcdf4`

##### Linux: 
* package names similar to OS X / Macports

##### Windows (untested):
* Enthought Canopy (https://www.enthought.com)  
  * Free version available which excludes... support for plotting maps

## 2.2 Running Python code

Two options:
1. Write code in a script (.py extension), call Python interpreter (`$ python xx.py`)
2. Run code in interactive Python shell (IPython), great for development / debugging: 
  * Allows you to run scripts, interactively type code, access variables, etc.

Example IPython (start from command line with `ipython`):

#### Script: hello_world.py  
`print('hello world!')`  
`pi = 3.1415`


In [138]:
run hello_world.py

hello world!


Directly access variables in Python interpreter:

In [139]:
3*pi

9.4245

## 2.3 Python extensions
Python standard library provides basic functionality, often useful (or necessary) to extend

Useful (for us..) examples:
1. NumPy: multi-dimensional arrays + functions to manipulate them (Chiel's talk)
2. matplotlib: basic plots (line, scatter, contour, ..)
3. Basemap: plotting of maps (Sebastian's talk)
4. NetCDF4: reading / writing netCDF files

#### How to use the extensions: import statement

In [140]:
import numpy # import using default name
numpy.zeros(2), numpy.ones(2)

(array([ 0.,  0.]), array([ 1.,  1.]))

In [141]:
import numpy as np # abbreviated name
np.zeros(2), np.ones(2)

(array([ 0.,  0.]), array([ 1.,  1.]))

In [142]:
reset -f 

In [143]:
from numpy import zeros # specific import
ones(2) # undefined

NameError: name 'ones' is not defined

In [144]:
from numpy import * # import everything
zeros(2), ones(2)

(array([ 0.,  0.]), array([ 1.,  1.]))

`import *` can by tricky:

In [145]:
pi = 0
from numpy import * # contains definition of pi
pi

3.141592653589793

In [146]:
reset -f 

## 2.4 Python basics
### 2.4.1 Variables

Python uses *duck typing*:
> *"If a bird looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck."*

In [147]:
var_1 = 1
var_2 = 1.
var_3 = "1"

type(var_1), type(var_2), type(var_3)

(int, float, str)

Explicit casting:

In [148]:
var_1 = float(1)
var_2 = int(1.)
var_3 = float("1")

type(var_1), type(var_2), type(var_3)

(float, int, float)

### Strings

In [149]:
s1 = 'Im a string!'
s2 = "me too!"

String formating from data/variables:

In [150]:
import numpy as np

a = 'pi = %8.4f'%np.pi               # Old style
b = 'pi = {0:8.4f}'.format(np.pi)    # New style
a,b

('pi =   3.1416', 'pi =   3.1416')

In [151]:
a = '{}'.format(np.pi)               # minimal
b = '{} {}'.format(np.pi, np.e)      # multiple numbers
c = '{1} {0}'.format(np.pi, np.e)    # indicate order
d = '{0:6.2f}'.format(np.pi)         # specify width / decimals
e = '{0:<6.2f}'.format(np.pi)        # alignment

a, b, c, d, e

('3.141592653589793',
 '3.141592653589793 2.718281828459045',
 '2.718281828459045 3.141592653589793',
 '  3.14',
 '3.14  ')

(Nearly) infinite number of possibilities, see e.g. https://pyformat.info for examples 

### 2.4.2 Data structures

#### 2.4.2.1 Lists: constructor [a,b,c]

In [152]:
time = [0,1,2,3,4,5,6,7,8,9]

Values accesible based on index or slice:  

In [153]:
time[0], time[1:4], time[0:6:2]

(0, [1, 2, 3], [0, 2, 4])

*Note that indexing starts at zero, slicing exludes last element*

Lists sizes can directly be changed:

In [154]:
time.append(10) # Append a value
time.remove(0)  # Remove first occurance of value
time.pop(5)     # Remove an element
time

[1, 2, 3, 4, 5, 7, 8, 9, 10]

#### 2.4.2.2 Tuples: constructor (a,b,c) 
Like a list, but not mutable

In [155]:
stations = ('hamburg','cabauw','karlsruhe')
stations

('hamburg', 'cabauw', 'karlsruhe')

After defining them, unable to change, append or remove items

#### 2.4.2.3 Dictionaries: constructor {'a':0, 'b':1}
Combination of keys and values, values accesible by keys:

In [156]:
data = {'T': 290, 'q': 10e-3, 'u': -2}
data['T'], data['u']

(290, -2)

Are mutable:

In [157]:
data['T'] = 300  # Change element
data['v'] = 3    # Add element
data.pop('u')    # Remove element (or del data['u'])
data

{'T': 300, 'q': 0.01, 'v': 3}

#### 2.4.2.4 Numpy arrays

In [158]:
import numpy as np
a1 = np.zeros(4)  # Array initialized with zeros
a2 = np.ones(4)   #   "         "      "   ones
a3 = np.empty(4)  # Uninitialized array

Multi-dimensional arrays:

In [159]:
a4 = np.zeros((2,2,2))
a5 = np.zeros((2,2,2), dtype=np.int)

More information on Numpy arrays and how to efficiently use them in Chiel's talk

### 2.4.3 Objects
Python is object-oriented (OO); enough material to cover a one-week workshop, so I'll only provide a single useful example

Example: reading in multiple files

In [160]:
import netCDF4 as nc4

f1     = nc4.Dataset('data/drycblles_1.nc', 'r')
time1  = f1.variables["t"][:]
ustar1 = f1.variables["ustar"][:]
obuk1  = f1.variables["obuk"][:]
# and ~60 more variables

f2     = nc4.Dataset('data/drycblles_2.nc', 'r')
time2  = f2.variables["t"][:]
ustar2 = f2.variables["ustar"][:]
# etc.

f3     = nc4.Dataset('data/drycblles_3.nc', 'r')
time3  = f3.variables["t"][:]
# etc.

Lots of double code, every change (add/remove variable, ..) requires code change for every file

#### Object oriented approach:

In [161]:
import netCDF4 as nc4
 
class read_nc:    # class definition
    def __init__(self, file_name):    # constructor
        f = nc4.Dataset(file_name, 'r')
        
        self.time  = f.variables["t"][:]
        self.ustar = f.variables["ustar"][:]
        self.obuk  = f.variables["obuk"][:]
        # and 100 more variables
    
    def post_process(self):
        self.time_hour = self.time / 3600.
        
r1 = read_nc('data/drycblles_1.nc')    # instance of class
r2 = read_nc('data/drycblles_2.nc')    # instance of class
r3 = read_nc('data/drycblles_3.nc')    # ...

r1.time

array([    0.,   300.,   600.,   900.,  1200.,  1500.,  1800.,  2100.,
        2400.,  2700.,  3000.,  3300.,  3600.,  3900.,  4200.,  4500.,
        4800.,  5100.])

In [162]:
r1.post_process()
r1.time_hour[:4]

array([ 0.        ,  0.08333333,  0.16666667,  0.25      ])

### 2.4.4 Loops

Two options: `for:` and `while:`

In [163]:
for i in range(2): # equivalent to range(0,2)
    print(i)

0
1


In [164]:
i = 10
while i > 1:
    i /= 2   # i = i / 2

Indentation determines body of loop:

In [165]:
for i in range(2):
    for j in range(2):
        for k in range(2):
            pass # i.e. do nothing
        # part of j-loop

Python is not very strict on indentation:

In [166]:
for i in range(1):
 pass
for i in range(1):
                   pass
for i in range(1):
         pass

for i in range(1):
             for j in range(1):
              for k in range(1):
                                 pass

> *"How To Write Unmaintainable Code and Ensure a job for life ;-)"*
https://www.thc.org/root/phun/unmaintain.html

### 2.4.4 Functions

In [167]:
cp = 1004.
Rd = 287.
def exner(p, p0):
    return (p/p0)**(Rd/cp)

exner(90000, 1e5)  

0.970331031603382

Default arguments are possible:

In [168]:
def exner(p, p0=1e5):
    return (p/p0)**(Rd/cp)

exner(90000), exner(90000,101300)

(0.970331031603382, 0.9667549928755136)

Easy to operate on arrays:

In [169]:
import numpy as np

def exner(p, p0=1e5):
    return (p/p0)**(Rd/cp)

p = np.linspace(70000, 101300, 10)
exner(p)

array([ 0.90306759,  0.91567175,  0.92785679,  0.93965467,  0.95109368,
        0.96219894,  0.97299292,  0.98349577,  0.99372566,  1.00369901])

### 2.4.5 Cleaning up

No deallocation needed (Garbage collector):

In [170]:
import numpy as np

f1 = np.arange(512**3)  # 1 GB memory
f1 = None               # 1 GB array released

If needed / wanted, de-allocation possible:

In [171]:
f1 = np.arange(512**3)  # 1 GB memory
del f1                  # 1 GB array released

# 2 Code examples
## 2.1 Input & output
### 2.1.1 Text files

In [172]:
import numpy as np

z  = np.linspace(0,100,6)    # Height [m]
th = 290 + 0.006*z           # Potential temperature [K]
qt = np.zeros_like(z)        # Specific humidity [kg/kg]

th[-1] = -9999               # Missing data
qt[-2] = -9999               # Missing data

z, th, qt

(array([   0.,   20.,   40.,   60.,   80.,  100.]),
 array([  290.  ,   290.12,   290.24,   290.36,   290.48, -9999.  ]),
 array([    0.,     0.,     0.,     0., -9999.,     0.]))

Write data to text file:

In [173]:
f = open('data/data.txt', 'w')  # w=write, r=read, ..
f.write('{0:^15s} {1:^15s} {2:^15s}\n'.format('z','theta [K]','q [kg/kg]'))
for k in range(z.size):
    f.write('{0:+1.8E} {1:+1.8E} {2:+1.8E}\n'.format(z[k], th[k], qt[k]))
f.close()

In [174]:
!cat data/data.txt

       z           theta [K]       q [kg/kg]   
+0.00000000E+00 +2.90000000E+02 +0.00000000E+00
+2.00000000E+01 +2.90120000E+02 +0.00000000E+00
+4.00000000E+01 +2.90240000E+02 +0.00000000E+00
+6.00000000E+01 +2.90360000E+02 +0.00000000E+00
+8.00000000E+01 +2.90480000E+02 -9.99900000E+03
+1.00000000E+02 -9.99900000E+03 +0.00000000E+00


Reading the same data:

In [175]:
f  = np.loadtxt('data/data.txt', skiprows=1) # returns 2D array [rows, columns]
z  = f[:,0]
th = f[:,1]
qt = f[:,2]

z,th,qt
th[1]

290.12

### 2.1.-1 Intermezzo: dealing with bad/missing data

Our data has some missing values (-9999)

In [176]:
th, qt

(array([  290.  ,   290.12,   290.24,   290.36,   290.48, -9999.  ]),
 array([    0.,     0.,     0.,     0., -9999.,     0.]))

Numpy has the possibility to mask arrays, either manually:

In [177]:
a = np.ma.zeros(5)
a[3] = np.ma.masked
a

masked_array(data = [0.0 0.0 0.0 -- 0.0],
             mask = [False False False  True False],
       fill_value = 1e+20)

Or based on existing data + criteria:

In [178]:
th_m = np.ma.masked_where(th == -9999, th) 
qt_m = np.ma.masked_where(qt == -9999, qt)
th_m

masked_array(data = [290.0 290.12 290.24 290.36 290.48 --],
             mask = [False False False False False  True],
       fill_value = 1e+20)

Masked values are exluded from statistics, plots, etc.:

In [179]:
th.mean(), th_m.mean()

(-1424.6333333333332, 290.24000000000001)

Masks are propagated:

In [180]:
th_m + qt_m

masked_array(data = [290.0 290.12 290.24 290.36 -- --],
             mask = [False False False False  True  True],
       fill_value = 1e+20)

### 2.1.2 NetCDF
Writing a NetCDF file, with dimensions, attributes, ...:

In [181]:
import netCDF4 as nc4

nc = nc4.Dataset('data/data.nc', 'w')                       # Create new dataset
nc.createDimension('z', z.size)                             # Create dimension
nc.setncattr('source', 'AES Python workshop')               # Set global attributes

# Create variables and set attributes:
nc_z = nc.createVariable('z', 'f8', 'z')                                        
nc_z.setncattr('units', 'm')
nc_z.setncattr('long_name', 'height above surface')

nc_th = nc.createVariable('th', 'f8', 'z', fill_value=-9999)                                        
nc_th.setncattr('units', 'K')
nc_th.setncattr('long_name', 'potential temperature')

nc_qt = nc.createVariable('qt', 'f8', 'z', fill_value=-9999)                                        
nc_qt.setncattr('units', 'kg kg-1')
nc_th.setncattr('long_name', 'specific humidity')

# Write data to file:
nc_z [:] = z  
nc_th[:] = th
nc_qt[:] = qt

nc.close()

In [182]:
!ncdump -v th data/data.nc

netcdf data {
dimensions:
	z = 6 ;
variables:
	double z(z) ;
		z:units = "m" ;
		z:long_name = "height above surface" ;
	double th(z) ;
		th:_FillValue = -9999. ;
		th:units = "K" ;
		th:long_name = "specific humidity" ;
	double qt(z) ;
		qt:_FillValue = -9999. ;
		qt:units = "kg kg-1" ;

// global attributes:
		:source = "AES Python workshop" ;
data:

 th = 290, 290.12, 290.24, 290.36, 290.48, _ ;
}


Reading a netCDF file:

In [183]:
nc = nc4.Dataset('data/data.nc', 'r')
z  = nc.variables['z'][:]
th = nc.variables['th'][:]
qt = nc.variables['qt'][:]

th

masked_array(data = [290.0 290.12 290.24 290.36 290.48 --],
             mask = [False False False False False  True],
       fill_value = -9999.0)

`fill_value` is automatically masked

# 2 Documentation / getting help

### Online resources:
* Python: https://www.python.org/doc/
* Numpy: http://docs.scipy.org/doc/
* Matplotlib: http://matplotlib.org/contents.html

### Ipython help function:
Typing e.g. `np.zeros?` in IPython will give you basic documentation

### Getting help:
* Python-friends mailing list (before at ZMAW, now at LRZ)
* Stackoverflow (478034 Python related questions)





